# Site settings
title: OpenCV library
email: admin@opencv.org
description: Official OpenCV library site
baseurl: ""
url: "http://opencv.org"
twitter_username: opencvlibrary
github_username:  opencv

# Build settings
markdown: kramdown
exclude: ["_scripts", "docker-compose.yml", "README.md", "vendor"]
gems:
    - jekyll-sitemap
sass:
  style: expanded
  deploy_style: compressed

collections:
    events:
      output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "events"
    values:
      layout: "event"


# Some constants
link_email: "mailto:admin@opencv.org"
link_sf: "https://sourceforge.net/projects/opencvlibrary"
link_gh: "https://github.com/opencv"
link_issues: "https://github.com/opencv/opencv/issues"
link_wiki: "https://github.com/opencv/opencv/wiki"
link_fb: "https://www.facebook.com/opencvlibrary"
link_gplus: "https://plus.google.com/+OpencvOrg"
link_twitter: "https://twitter.com/opencvlibrary"
link_youtube: "https://www.youtube.com/user/opencvdev"
link_forum: "http://answers.opencv.org"
link_docs: "http://docs.opencv.org"
link_ci: "http://pullrequest.opencv.org"
